addr: "127.0.15.1"
port: 8080

db_host: "127.0.0.1"
db_port: 5432
db_name: "keystore"
db_username: "keykeeper"
db_password: "CHANGE_PASSWORD"

timezone: "Europe/Zaporozhye"
token_lifetime: 744             # 31 * 24

salt: "test_SaLtT"